Add retry to deploy since the server is acting up

diff --git a/.github/workflows/build-test-push-deploy.yml b/.github/workflows/build-test-push-deploy.yml
--- a/.github/workflows/build-test-push-deploy.yml
+++ b/.github/workflows/build-test-push-deploy.yml
@@ -51,7 +51,15 @@ jobs:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
       - name: Update known_hosts
-        run: ssh-keyscan openchart.io >> ~/.ssh/known_hosts
+        run: |
+          set +e
+          for i in {1..10}; do
+            ssh-keyscan openchart.io >> ~/.ssh/known_hosts \
+              && exit 0
+            echo "ssh-keyscan failed, retrying..."
+            sleep 2
+          done
+          exit 1
 
       - name: Setup Docker context
         run: |
@@ -59,4 +67,12 @@ jobs:
           docker context use openchart
 
       - name: Deploy
-        run: docker stack deploy -c docker/docker-compose.yml openchart
+        run: |
+          set +e
+          for i in {1..10}; do
+            docker stack deploy -c docker/docker-compose.yml openchart \
+              && exit 0
+            echo "deploy failed, retrying..."
+            sleep 2
+          done
+          exit 1
